"""clients opportunities audit_logs

Revision ID: 1800480e269d
Revises: 24cf4518e31d
Create Date: 2026-08-31 12:52:40.650366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1800480e269d'
down_revision: Union[str, None] = '24cf4518e31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('commercial_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_business_name'), ['business_name'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('previous_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('audit_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audit_type', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('number_of_days', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('travel_expenses', sa.String(length=20), nullable=False),
    sa.Column('lodging', sa.String(length=20), nullable=False),
    sa.Column('transportation', sa.String(length=20), nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('auditors_required', sa.Integer(), nullable=False),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_opportunities_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_opportunities_folio'), ['folio'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_opportunities_status'), ['status'], unique=False)

    op.create_table('opportunity_competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['audit_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'competency_id', name='uq_opportunity_competency')
    )
    with op.batch_alter_table('opportunity_competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_competencies_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_competencies_opportunity_id'), ['opportunity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_competencies_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_competencies_competency_id'))

    op.drop_table('opportunity_competencies')
    with op.batch_alter_table('audit_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_opportunities_status'))
        batch_op.drop_index(batch_op.f('ix_audit_opportunities_folio'))
        batch_op.drop_index(batch_op.f('ix_audit_opportunities_client_id'))

    op.drop_table('audit_opportunities')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_business_name'))

    op.drop_table('clients')
    # ### end Alembic commands ###
