"""auditors competencies matrix

Revision ID: 24cf4518e31d
Revises: 833e42025f96
Create Date: 2026-08-31 11:16:18.065988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24cf4518e31d'
down_revision: Union[str, None] = '833e42025f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competencies_name'), ['name'], unique=True)

    op.create_table('auditors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_id', sa.String(length=30), nullable=True),
    sa.Column('bank_information', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditors_user_id'), ['user_id'], unique=True)

    op.create_table('auditor_competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('certificate_number', sa.String(length=80), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditors.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auditor_id', 'competency_id', name='uq_auditor_competency')
    )
    with op.batch_alter_table('auditor_competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditor_competencies_auditor_id'), ['auditor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditor_competencies_competency_id'), ['competency_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditor_competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditor_competencies_competency_id'))
        batch_op.drop_index(batch_op.f('ix_auditor_competencies_auditor_id'))

    op.drop_table('auditor_competencies')
    with op.batch_alter_table('auditors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditors_user_id'))

    op.drop_table('auditors')
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competencies_name'))

    op.drop_table('competencies')
    # ### end Alembic commands ###
