"""personal catalog

Revision ID: 5210ed69f7c9
Revises: 9f1a2b3c0001
Create Date: 2026-09-02 11:22:23.228293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5210ed69f7c9'
down_revision: Union[str, None] = '9f1a2b3c0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_nombre_completo'), ['nombre_completo'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('personal_areas',
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('personal_id', 'area_id')
    )
    op.create_table('personal_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_emails_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_personal_emails_personal_id'), ['personal_id'], unique=False)
        batch_op.create_index('uq_personal_emails_principal', ['personal_id'], unique=True, postgresql_where=sa.text('principal = TRUE'), sqlite_where=sa.text('principal = TRUE'))

    op.create_table('personal_roles',
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('personal_id', 'rol_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_roles')
    with op.batch_alter_table('personal_emails', schema=None) as batch_op:
        batch_op.drop_index('uq_personal_emails_principal', postgresql_where=sa.text('principal = TRUE'))
        batch_op.drop_index(batch_op.f('ix_personal_emails_personal_id'))
        batch_op.drop_index(batch_op.f('ix_personal_emails_email'))

    op.drop_table('personal_emails')
    op.drop_table('personal_areas')
    op.drop_table('roles')
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_nombre_completo'))

    op.drop_table('personal')
    op.drop_table('areas')
    # ### end Alembic commands ###
