"""applications

Revision ID: 6ac03060591d
Revises: 1800480e269d
Create Date: 2026-08-31 13:20:22.050072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac03060591d'
down_revision: Union[str, None] = '1800480e269d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditors.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['audit_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'auditor_id', name='uq_application_auditor')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_auditor_id'), ['auditor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_opportunity_id'), ['opportunity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_applications_auditor_id'))

    op.drop_table('applications')
    # ### end Alembic commands ###
