"""assignments

Revision ID: d39eb2e9f62e
Revises: 6ac03060591d
Create Date: 2026-08-31 13:30:42.918194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39eb2e9f62e'
down_revision: Union[str, None] = '6ac03060591d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('travel_expenses', sa.String(length=20), nullable=False),
    sa.Column('lodging', sa.String(length=20), nullable=False),
    sa.Column('transportation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditors.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['audit_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'auditor_id', name='uq_assignment_auditor')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_auditor_id'), ['auditor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_assignments_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_auditor_id'))

    op.drop_table('assignments')
    # ### end Alembic commands ###
